# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: f962da038b3e9389d1c4848a5796164436dcb933216cce13036a15703aa9473c69e1e1330b2df4e94ee2af31e248efa61e38977644cc4568010cb740ce585190

test:
  domain_name: example.com 
  secret_key_base: 6e91d3c411de75611c00b5efffb91a4869dab08063a2663b0a35bd448814b495823e059d6efd33ee6822cec633c140be2d8a86d37cf98b2f67d4da50f69231b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
